generate_outpatients.py
stores the OPA data in a new table before aggregation
=> creates a new table which is the ungrouped opa data

generate_outpatients.py
Closes https://github.com/The-Strategy-Unit/nhp_planning/issues/80
=> adds "maternity" to "type" in OP

inputs_data/baseline.py
I'm a dummy and was overwriting another file. this corrects my stupidity
=> saves the data to the correct location 🤦‍♂

inputs_data/ip/__init__.py
adds the missing general length of stay mitigators to the inputs app. fixes #54
=> adds general los mitigators to inputs pipeline

inputs_data/ip/diagnoses.py, inputs_data/ip/procedures.py
was simply counting the records, rather than summing the sample rate, overstating the amount of records for a mitigator
=> switches to summing sample rate for diag/proc table

inputs_data/age_sex.py
previously we filtered the data that was shown in the inputs app pyramid charts to ensure there was at least 5 bits of activity per age/sex group. this restores that filter
=> filters age/sex data for inputs app to ensure n > 5

nhp_datasets/icbs.py, raw_data/aae.py, raw_data/ecds.py, raw_data/inpatients.py, raw_data/outpatients.py
changed main icb into a function to remove a circular dependency
=> fix issue of circular dependency for main icb

raw_data/inpatients_mitigators.py
in workflows it doesn't display the progress, so no point in including it
=> removes tqdm from inpatient mitigators

databricks_workflows/extract_nhp_for_containers.yaml, model_data/health_status_adjustment/generate_gams.py, model_data/health_status_adjustment/generate_national_gams.py, model_data/model_data_extract.py
move the notebooks from nhp_model which extract the data for the model and generate the HSA gams.
=> Move notebooks from nhp_model

raw_data/mitigators/ip/efficiency/same_day_emergency_care.py
see https://github.com/The-Strategy-Unit/nhp_inputs/pull/463
=> Update sdec documentation

model_data/health_status_adjustment/generate_gams.py
- some logic issues were causing rows to be created which always ended up with 0 activity, this caused the gams to never converge, which caused too much output, which killed the databricks task 🤦‍♂️
- added some simple progress monitoring
=> Fix GAMs part deux

databricks_workflows/nhp_data-population_projections.yaml, population_projections/npp.py, population_projections/snpp.py
fixes incorrect names used for some projections
=> fixes issue with variant projections

raw_data/mitigators/__init__.py, raw_data/mitigators/ip/activity_avoidance/alcohol.py, raw_data/mitigators/ip/activity_avoidance/ambulatory_care_conditions.py, raw_data/mitigators/ip/activity_avoidance/cancelled_operations.py, raw_data/mitigators/ip/activity_avoidance/eol_care.py, raw_data/mitigators/ip/activity_avoidance/evidence_based_interventions.py, raw_data/mitigators/ip/activity_avoidance/falls_related_admissions.py, raw_data/mitigators/ip/activity_avoidance/frail_elderly.py, raw_data/mitigators/ip/activity_avoidance/intentional_self_harm.py, raw_data/mitigators/ip/activity_avoidance/medically_unexplained_related_admissions.py, raw_data/mitigators/ip/activity_avoidance/medicines_related_admissions.py, raw_data/mitigators/ip/activity_avoidance/obesity_related_admissions.py, raw_data/mitigators/ip/activity_avoidance/raid_ae.py, raw_data/mitigators/ip/activity_avoidance/readmission_within_28_days.py, raw_data/mitigators/ip/activity_avoidance/smoking_related_admissions.py, raw_data/mitigators/ip/activity_avoidance/zero_los_no_procedure.py, raw_data/mitigators/ip/efficiency/day_procedures.py, raw_data/mitigators/ip/efficiency/emergency_elderly.py, raw_data/mitigators/ip/efficiency/enhanced_recovery.py, raw_data/mitigators/ip/efficiency/excess_beddays.py, raw_data/mitigators/ip/efficiency/preop_los.py, raw_data/mitigators/ip/efficiency/raid_ip.py, raw_data/mitigators/ip/efficiency/same_day_emergency_care.py, raw_data/mitigators/ip/efficiency/stroke_early_supported_discharge.py, raw_data/mitigators/ip/shared/virtual_wards.py
the apc table is partitioned by fyear/provider, so adding in these columns will improve performance
=> adds the fyear/provider partition columns to mitigators table

model_data/extract_apc_data.py, model_data/extract_birth_factors_data.py, model_data/extract_demographic_factors_data.py, model_data/extract_ecds_data.py, model_data/extract_opa_data.py, model_data/helpers.py, model_data/model_data_extract.py
=> Split model data extract into separate files

databricks_workflows/extract_nhp_for_containers.yaml, model_data/aae.py, model_data/birth_factors.py, model_data/demographic_factors.py, model_data/ip.py, model_data/op.py
all files now have a single extract() function, and the files are named to (mostly) match the location where we extract the data to.
inpatient mitigators are grouped into the inpatient extract in ip.py
=> renames files to match the folder structure

databricks_workflows/extract_nhp_for_containers.yaml, model_data/ip.py
=> fixes the extract workflow

databricks_workflows/nhp_data-population_projections.yaml, population_projections/get_ons_files_2022.py, population_projections/npp.py, population_projections/snpp.py
* adds script to download the 2022-based population projections from ONS
* updates scripts to use the new files
* updates workflow to extract 2022 data
closes #95
=> Add 2022 pop projections

model_data/birth_factors.py, model_data/demographic_factors.py, model_data/helpers.py
- **fixes demographics extracts**
- **fix issue with birth factors**
=> fix demographic extract

nhp_datasets/apc.py, raw_data/aae.py, raw_data/ecds.py, raw_data/outpatients.py
previously, we ensured all rows had valid age values (needed for demographic adjustment).
this reinstates this, and ensures all of the datasets filter in a consistent way.
=> ensures all datasets have age filter

aggregated_data/ecds.py, aggregated_data/outpatients.py, inputs_data/ae/__init__.py, inputs_data/helpers.py, inputs_data/ip/__init__.py, inputs_data/op/__init__.py, raw_data/aae.py, raw_data/ecds.py, raw_data/helpers.py, raw_data/inpatients.py, raw_data/outpatients.py
There are a couple of columns which are created in `nhp_model` which should be in `nhp_data` instead, as they are used downstream.
=> move steps from nhp_model into nhp_data

raw_data/helpers.py
=> fixes typo in function call

inputs_data/op/__init__.py
=> removes maternity 'mitigators' from inputs data

inputs_data/wli.py, reference/get_rtt_year_end_incompletes.py
=> adds script to get the rtt incompletes data

src/nhp/data/raw_data/mitigators/ip/activity_avoidance/evidence_based_interventions.py
*args should be the type, not a list of the type
working towards resolving https://github.com/The-Strategy-Unit/nhp_data/issues/193, but does not close the issue
=> fix typing on evidence based interventions

src/nhp/data/inputs_data/ae/__init__.py, src/nhp/data/inputs_data/ae/diagnoses.py, src/nhp/data/inputs_data/ae/expat_repat.py, src/nhp/data/inputs_data/ae/procedures.py, src/nhp/data/inputs_data/ip/__init__.py, src/nhp/data/inputs_data/ip/expat_repat.py, src/nhp/data/inputs_data/op/__init__.py, src/nhp/data/inputs_data/op/expat_repat.py, src/nhp/data/nhp_datasets/apc.py, src/nhp/data/raw_data/aae.py, src/nhp/data/raw_data/ecds.py, src/nhp/data/raw_data/helpers.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/readmission_within_28_days.py, src/nhp/data/reference/day_procedures.py, src/nhp/data/reference/population_by_imd_decile.py, src/nhp/data/reference/provider_main_icb.py
- **fixes typing of F.col(...).isNotNull by switching to F.isnotnull**
- **same, but for isNull -> isnull**
working towards resolving https://github.com/The-Strategy-Unit/nhp_data/issues/193, but does not close the issue
=> fix typing is not null

src/nhp/data/population_projections/get_ons_files_2022.py, src/nhp/data/raw_data/aae.py, src/nhp/data/raw_data/ecds.py, src/nhp/data/raw_data/inpatients.py, src/nhp/data/raw_data/outpatients.py, src/nhp/data/raw_data/outpatients_mitigators.py
some functions did used to "return" None, but now return DataFrame's
working towards resolving https://github.com/The-Strategy-Unit/nhp_data/issues/193, but does not close the issue
=> fixes return types of functions

src/nhp/data/raw_data/mitigators/ip/activity_avoidance/alcohol.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/ambulatory_care_conditions.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/eol_care.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/evidence_based_interventions.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/evidence_based_interventions_ent.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/evidence_based_interventions_general_surgery.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/evidence_based_interventions_gi_surgical.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/evidence_based_interventions_msk.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/evidence_based_interventions_urology.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/evidence_based_interventions_vascular_varicose_veins.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/falls_related_admissions.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/intentional_self_harm.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/medically_unexplained_related_admissions.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/medicines_related_admissions.py, src/nhp/data/raw_data/mitigators/ip/activity_avoidance/raid_ae.py, src/nhp/data/raw_data/mitigators/ip/efficiency/day_procedures.py, src/nhp/data/raw_data/mitigators/ip/efficiency/enhanced_recovery.py, src/nhp/data/raw_data/mitigators/ip/efficiency/raid_ip.py, src/nhp/data/raw_data/mitigators/ip/shared/virtual_wards.py
might be better to refactor the code to do away with the monkey-patched admission_has/not methods, as these make it almost impossible to get the typing right
working towards resolving https://github.com/The-Strategy-Unit/nhp_data/issues/193, but does not close the issue
=> adds ty: ignore for monkey-patched methods

src/nhp/data/model_data/inequalities.py
Solves bug of missing parquet files where providers do not have valid inequalities
=> add missing providers to inequalities extract

src/nhp/data/raw_data/helpers.py
=> uses correct specialty code
